version: '3.8'

services:
  macos-emulator:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: macos-emulator:latest
    container_name: macos-safari
    privileged: true
    ports:
      - "5900:5900"    # VNC
      - "6080:6080"    # Web VNC
      - "22:22"        # SSH
    volumes:
      - macos_data:/home/user/OSX-KVM
      - ./configs:/configs:ro
      - ./scripts:/scripts:ro
    environment:
      - DISPLAY=:0
      - VNC_PASSWORD=password
      - RAM=8192
      - CPU_CORES=4
      - ENABLE_VNC=true
      - ENABLE_SSH=true
    devices:
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    restart: unless-stopped
    networks:
      - macos_network

  vnc-web:
    image: dorowu/ubuntu-desktop-lxde-vnc:latest
    container_name: vnc-web-access
    ports:
      - "6081:80"
    environment:
      - VNC_PASSWORD=password
      - RESOLUTION=1920x1080
    volumes:
      - vnc_data:/root
    depends_on:
      - macos-emulator
    networks:
      - macos_network

volumes:
  macos_data:
    driver: local
  vnc_data:
    driver: local

networks:
  macos_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16