#!/usr/bin/env bash

if [ -d "./bin" ]; then
  echo "Error: The current directory is not empty. Please remove all contents within this directory and try again."
  exit 1
fi

# Ensure these are created so Docker doesn't create them as root
mkdir -p ~/.composer ~/.ssh
