services:
  app:
    volumes: &appvolumes
      ## Host mounts with performance penalty, only put what is necessary here
      - ./src/grunt-config.json.sample:/var/www/html/grunt-config.json:cached
      - ./src/Gruntfile.js.sample:/var/www/html/Gruntfile.js:cached
      - ./src/dev/tools/grunt/configs:/var/www/html/dev/tools/grunt/configs:cached
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./src/package.json.sample:/var/www/html/package.json:cached
      - ./src/generated:/var/www/html/generated:cached
      - ./src/var:/var/www/html/var:cached
      - ./env/xdebug.ini:/usr/local/etc/php/conf.d/custom.ini
      #- ./src/auth.json:/var/www/html/auth.json:cached
      #- ./src/m2-hotfixes:/var/www/html/m2-hotfixes:cached
      #- ./src/patches:/var/www/html/patches:cached

  phpfpm:
    volumes: *appvolumes
