services:
  app:
    volumes: &appvolumes
      ## Host mounts with performance penalty, only put what is necessary here
      - ./grunt-config.json.sample:/var/www/html/grunt-config.json:cached
      - ./Gruntfile.js.sample:/var/www/html/Gruntfile.js:cached
      - ./dev/tools/grunt/configs:/var/www/html/dev/tools/grunt/configs:cached
      - ./nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./package.json.sample:/var/www/html/package.json:cached
      - ./generated:/var/www/html/generated:cached
      - ./var:/var/www/html/var:cached
      - ./src/bin:/var/www/html/bin:cached
      - ./env/xdebug.ini:/usr/local/etc/php/conf.d/custom.ini
      #- ./auth.json:/var/www/html/auth.json:cached
      #- ./m2-hotfixes:/var/www/html/m2-hotfixes:cached
      #- ./patches:/var/www/html/patches:cached

  phpfpm:
    volumes: *appvolumes

#  phpmyadmin:
#    image: linuxserver/phpmyadmin
#    env_file: env/db.env
#    ports:
#      - "8080:80"
#    depends_on:
#      - db
#    networks:
#      - app_network
